### ISSUE TITLE
Do we need to support `#contentProfiles` or `#processorProfiles`?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/adpt#10]
TTML2 requires support for the [`#contentProfiles`](https://www.w3.org/TR/ttml2/#feature-contentProfiles) and [`#processorProfiles`](https://www.w3.org/TR/ttml2/#feature-processorProfiles) features in both the [TTML2 Transformation Profile](https://www.w3.org/TR/ttml2/#profile-ttml2-transformation) and the [TTML2 Presentation Profile](https://www.w3.org/TR/ttml2/#profile-ttml2-presentation).

Those features permit documents to signal which processor type is needed to process them, and to signal their content conformance. These signalling requirements are often not considered in early versions of a specification, but including them allows for future use more easily by allowing later processors to process earlier documents with the appropriate constraints that apply to those documents.

It also means that earlier processors can identify if they cannot process documents that conform to later versions of a specification, if new required features are added, for example.

I do not think we can require the syntax to be present in documents, but we should require support the features from the beginning.

**Comment by simpson-matt** [comment]
So we permit people to specify, but don't require them to; makes sense to me - as I think there is an increasing interest in automated voicing of AD in some new markets that could benefit here.

**Comment by nigelmegitt** [comment]
From the comment from @simpson-matt and [the call today](https://www.w3.org/2019/06/10-audio-description-minutes.html#x04), I believe we have consensus to go ahead with support for these features, so I will prepare a pull request for it.
