### ISSUE TITLE
Explore potential opportunities for extended descriptions

### ISSUE THREAD

**Issue by a11ycob** [w3c/adpt#14]
[Extended video descriptions](https://www.w3.org/WAI/PF/media-a11y-reqs/#extended-video-descriptions), as a concept, has existed for some time. However, it is not currently reflected in a meaningful way in any of the W3C work (that I am aware of). Is there an opportunity to explore this topic?
Questions: Is this functionality that needs to be described by this document, or is it a player level solution?

**Comment by nigelmegitt** [comment]
Thanks for raising this @a11ycob 

As discussed on the call on Monday, this is something I think we do not need to address with any detailed technical solutions in the first version, however we could certainly add a note that player implementations may reasonably offer a mode in which the main media playback is paused until a description has completed, whether that description is provided as pre-recorded audio or by text to speech, or indeed by rendering onto a Braille display.

I do not _think_ any change to the document format is needed for this, but I'd happily take any feedback from implementers. For example, do we need a semantic indication to determine whether an element with an audio child requires pausing until completion?

From an implementation perspective I would be interested to know if the required information is available at playback time to know when the description has been completed:
* For an `audio` element, the referenced audio has a knowable duration (either a `clipBegin` and `clipEnd` time or the native duration of the referenced audio)
* For a description being spoken with text to speech, for example using the Web Speech API, is there a "speaking completed" event?
* For a description being presented by a screen reader, is there a "screen reader presentation completed" event?

**Comment by nigelmegitt** [comment]
Closing since work on ADPT has moved to DAPT. See w3c/dapt#71 for the equivalent discussion.
