### ISSUE TITLE
Reassign the repository to Timed Text Working Group

### ISSUE THREAD

**Issue by plehegar** [w3c/adpt#20]
- [x] Update w3c.json #19 
- [x] Update the [repository manager](https://labs.w3.org/repo-manager/repos)
- [x] Update [notify-ml-config](https://github.com/w3c/github-notify-ml-config/blob/master/mls.json#L633) to include the repository in notification for public-tt
- [x] Update [README](https://github.com/w3c/adpt/blob/master/README.md)

**Comment by nigelmegitt** [comment]
I've done the first two things, but I'm not sure how to go about updating notify-ml-config - can I leave that with you @himorin ?

**Comment by plehegar** [comment]
sure. I meant those things to be assigned to him.

@himorin , see [mls.json](https://github.com/w3c/github-notify-ml-config/blob/master/mls.json#L633)

**Comment by himorin** [comment]
sorry for late catching, added two PRs for last two items.

**Comment by plehegar** [comment]
thx. I also added the horizontal review labels for issues and pull requests (I have a script for that).

**Comment by nigelmegitt** [comment]
Closing since all the tasks have been completed.
