### ISSUE TITLE
Prohibit the same audio resource from being played more than once at the same time

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/adpt#22]
Through experimentation, I have found that browser playback of multiple `<audio>` elements with the same source URL can cause issues. 

In the condition that an ADPT document specifies multiple audio resources whose playback does not overlap in time, but which all have the same `src` URL, for example because they use `@clipBegin` and `@clipEnd` to play different subsections, one implementation approach in Javascript is to create a separate `Audio` object for each one.

However, when testing this, on Firefox, some of them don't load the data, presumably because the browser is trying to keep a lid on resource usage. The result is that although `play()` is called, the resource sits in a waiting state, often for longer than the required duration! The result for the user is that the description audio doesn't play, and it is unpredictable which descriptions this affects.

Caching the `Audio` element on a per-URL basis, and reusing it, solves the issue. However this approach has a limitation, which is that if there is a requirement to play that audio more than once simultaneously, it won't work.

I'm pretty sure we already agreed that overlapping descriptions are not a requirement, but this implementation issue pushes me firmly into the "we should specify this prohibition" camp, to simplify implementations.

---
Update: this is similar to #8.

**Comment by gkatsev** [comment]
Often times, adding a unique query parameters to the sources is enough to distinguish the sources to the browser and remove any issues between playing back the "same" source in multiple audio elements.
However, it's probably easiest to just say you shouldn't do this.

**Comment by nigelmegitt** [comment]
That's a really good point @gkatsev , thanks. Actually that might be a reasonable workaround if people really want to make this behaviour work. After all, they could alternatively duplicate the audio and create multiple identical resources.

**Comment by eric-carlson** [comment]
> However, when testing this, on Firefox, some of them don't load the data, presumably because the browser is trying to keep a lid on resource usage. The result is that although play() is called, the resource sits in a waiting state, often for longer than the required duration! The result for the user is that the description audio doesn't play, and it is unpredictable which descriptions this affects.

That should definitely work, and a quick test shows it does in Safari. 

It sounds like a bug in Firefox, and I'm sure the developers would be happy if you filed a report.

**Comment by nigelmegitt** [comment]
Thanks for the great suggestion @eric-carlson. I am working on some demo material that I can circulate freely in order to show this specification working more generally, but also to be able to provide a test case for demonstrating this as a browser bug, before I raise such a bug report.

**Comment by btsimonh** [comment]
Yella Umbrella would not like to see this restricted.
Reason: our users can duplicate an audio take, then trim each duplicate (e.g. first half, second half).  We do this non-destructively (i.e. they both use the SAME audio file).  The user may well (and by default) overlap these two audios with a cross-fade between them.  This could be used to adjust timing between sentences, or even remove a section from a recording which is over length.

Example:
![image](https://user-images.githubusercontent.com/3137332/121352128-70003700-c924-11eb-8fdf-64c2d23d33ed.png)


About creating an audio element... I dropped this like a hot potato for short clips once I'd found audioCtx.decodeAudioData(data, ...).  

Playing an audio buffer is very efficient (once you have the audio buffer).  In my mind, it's just doing exactly the same thing as using an audio element, except you have far more control, and avoids issues like those above, and a whole bunch of code that we don't have use for.  Any you can play it as many times (and simultaneously) as you like...

For long clips things get much more complex.  i.e. you may not wish to download and decode 90 minutes of what will end up as stereo 32 bit float at 48khz.  IF playing part of a long clip using an audio element, you'd need to ensure that the original media file is tuned for random access and seekability, and hope the audio element actually does seek, and not download the lot first.
It would be possible (but not necessarily practical) to 'play' part of the file and capture to an audiobuffer.

e.g. if using DRMed original audio in Stellar (DASH mp4, even served from local server), seek times are FAR worse than when using a separate OGG file for audio scrubbing.

p.s. The webaudio guy for firefox was very responsive when I had questions in the webaudio slack channel a year ago.

**Comment by nigelmegitt** [comment]
Closing since work on this has moved to DAPT, but not losing this: opened w3c/dapt#170 to discuss constraints on audio resource playback within DAPT.
