### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by cconcolato** [w3c/adpt#4]
The abstract reads:
> Audio Description is usually delivered as audio, either pre-recorded or synthesised, but (until now) has not deliverable as accessible text. 

I don't understand this sentence. Should 'has' and 'deliverable' be deleted?

**Comment by cconcolato** [comment]
An additional typo in section 1:
> This profiles is intended to support audio description workflows worldwide

should be 'profile' no 's'.

**Comment by cconcolato** [comment]
In section 8.2, there is a link to "9.7 Profile Signaling" but a) the link is broken and b) the section "Profile Signaling" is number 9.6.

**Comment by cconcolato** [comment]
I'm not sure I understand the need for section 8.2 or why it has to be this complex but having the term "Profile" with a capital P is a bit confusing. Also there is one mention of "proposed Profile". Should "proposed" be removed?

**Comment by cconcolato** [comment]
Shouldn't overflow and overflow-visible be prohibited instead of permitted?

**Comment by nigelmegitt** [comment]
Thanks for the review @cconcolato this should be pretty quick to sort out, as it's all editorial, and I think we may need some bigger restructuring too.
